@startuml
start
:Получить данные о рейтинге пассажира;
if (Рейтинг больше 3 звезд?) then (да)
:Вывести предложение заказа на телефон водителя;
else (нет)
:Рейтинг пассажира ниже среднего. Будьте аккуратны!>
:Вывести предложение заказа на телефон водителя;
endif
:Ожидание согласия/отказа водителя на предложение заказа;
stop
@enduml