@startuml
start
repeat
while (Пассажир ждет больше 20 минут?) is (нет)
:Уважаемый клиент, подождите еще пару минут>
endwhile (да)
: Уважаемый клиент, предлагаем вам заказать другую машину>
: Вывести на экран кнопку "Заказать другую машину";
backward :Пожалуйста, ожидайте>
repeat  while (Пассажир заказал другую машину?) is (Нет) not (Да)
:Отправить заказ другому водителю;
stop
@enduml